/**
 * BrowserRenderer — client-side video rendering engine for VideoFlow.
 *
 * This renderer takes a compiled {@link VideoJSON} and produces video output
 * entirely in the browser using a per-layer rasterization pipeline:
 *
 * 1. **DOM-based frame rendering** — each layer is a DOM element whose CSS
 *    custom properties / inline styles are updated every frame via
 *    `renderFrame`.
 *
 * 2. **Per-layer SVG rasterization** — each visible layer is individually
 *    wrapped in an SVG `<foreignObject>` and decoded to a bitmap via
 *    `<img>.decode()`. Layers whose resolved properties haven't changed since
 *    the previous frame reuse the cached bitmap.
 *
 * 3. **Transition pipeline** — `applyTransitions()` (on `RuntimeBaseLayer`)
 *    mutates the per-frame property map before rasterization, applying any
 *    `transitionIn` / `transitionOut` preset registered via
 *    `BrowserRenderer.registerTransition`.
 *
 * 4. **WebGL effect pipeline** — layers with `effects` are piped through
 *    `WebGLEffectCompositor` after rasterization. Each declared effect runs as
 *    a GLSL fragment-shader pass (ping-pong FBOs). Effect params are
 *    animatable via dot-path keys (`effects.<name>.<param>`).
 *
 * 5. **Compositing** — rasterized (and optionally effected) bitmaps are drawn
 *    onto a shared `OffscreenCanvas` in layer order via `drawImage`.
 *
 * 6. **Audio rendering** — an `OfflineAudioContext` mixes all audio/video
 *    layers into a single `AudioBuffer`, honouring volume/pan/pitch keyframes.
 *
 * 7. **Video encoding** — frames and audio are fed into MediaBunny to produce
 *    an MP4 blob (H.264 + AAC) entirely client-side, with no server needed.
 *
 * Layer-specific behaviour is delegated to the runtime layer hierarchy in
 * `./layers/`. Transition and effect registries are in `./transitions.ts` and
 * `./effects.ts`; built-in presets are auto-registered via side-effect imports.
 */

import type { VideoJSON, RenderOptions, PropertyDefinition } from '@videoflow/core/types';
import { audioBufferToWav } from '@videoflow/core/utils';
import { loadedMedia } from '@videoflow/core';
import RENDERER_CSS from './renderer.css.js';
export { RENDERER_CSS };
import {
	Output,
	Mp4OutputFormat,
	BufferTarget,
	CanvasSource,
	AudioBufferSource,
	QUALITY_HIGH,
} from 'mediabunny';

import { createRuntimeLayer, RuntimeBaseLayer, type ILayerRenderer } from './layers/index.js';
import RuntimeGroupLayer from './layers/RuntimeGroupLayer.js';
import LayerRasterizer from './LayerRasterizer.js';
import WebGLEffectCompositor from './WebGLEffectCompositor.js';
import {
	registerTransition as registerTransitionInRegistry,
	type TransitionFn,
} from './transitions.js';
import {
	registerEffect as registerEffectInRegistry,
	type EffectParamDefinition,
} from './effects.js';
import { buildFontUrl } from './googleFontLoader.js';
import FontEmbedder from './FontEmbedder.js';
// Side-effect imports: auto-register the built-in transitions and effects.
import './transitions/presets.js';
import './effects/presets.js';

// Worker source — self-contained bundle (mediabunny inlined) generated by
// bundle-worker.ts. Loaded as a Blob URL at runtime so no file-URL resolution
// is needed, making it work across all bundlers (esbuild, Vite, webpack, etc.).
import WORKER_SOURCE from './workerBundle.js';

// ---------------------------------------------------------------------------
//  Audio encoder probe
//
//  WebCodecs `AudioEncoder` support varies across platforms:
//  - macOS / Windows Chrome: AAC available via system codecs.
//  - Linux Chrome (incl. headless): AAC encoder is NOT shipped due to
//    licensing. Opus is available everywhere as a fallback.
//
//  MP4 supports Opus officially (RFC 8606) and modern players (Chrome,
//  Firefox, Safari 17+, VLC) handle it. We prefer AAC for maximum
//  compatibility, fall back to Opus when AAC isn't available, and finally
//  encode silent video rather than crashing the whole render.
// ---------------------------------------------------------------------------

export type AudioCodecChoice = { codec: 'aac' | 'opus'; bitrate: number };

const AAC_BITRATE_CANDIDATES = [192_000, 128_000, 96_000];
const OPUS_BITRATE_CANDIDATES = [128_000, 96_000, 64_000];

export async function pickSupportedAudioCodec(
	numberOfChannels: number,
	sampleRate: number,
): Promise<AudioCodecChoice | null> {
	if (typeof AudioEncoder === 'undefined') return null;

	const probe = async (codec: string, bitrate: number) => {
		try {
			const r = await AudioEncoder.isConfigSupported({ codec, sampleRate, numberOfChannels, bitrate });
			return r.supported === true;
		} catch { return false; }
	};

	// Prefer AAC (universal MP4 player support).
	for (const bitrate of AAC_BITRATE_CANDIDATES) {
		if (await probe('mp4a.40.2', bitrate)) return { codec: 'aac', bitrate };
	}
	// Fall back to Opus.
	for (const bitrate of OPUS_BITRATE_CANDIDATES) {
		if (await probe('opus', bitrate)) return { codec: 'opus', bitrate };
	}
	return null;
}

// ---------------------------------------------------------------------------
//  Property definition registry — built from core layer classes
// ---------------------------------------------------------------------------

import {
	TextLayer, CaptionsLayer, ImageLayer, VideoLayer, AudioLayer, ShapeLayer, GroupLayer,
} from '@videoflow/core';

/**
 * Static registry mapping layer type → merged propertiesDefinition.
 * Avoids re-computing on every property lookup.
 */
const PROPERTIES_BY_TYPE: Record<string, Record<string, PropertyDefinition>> = {
	text: TextLayer.propertiesDefinition,
	captions: CaptionsLayer.propertiesDefinition,
	image: ImageLayer.propertiesDefinition,
	video: VideoLayer.propertiesDefinition,
	audio: AudioLayer.propertiesDefinition,
	shape: ShapeLayer.propertiesDefinition,
	group: GroupLayer.propertiesDefinition,
};

// ---------------------------------------------------------------------------
//  BrowserRenderer
// ---------------------------------------------------------------------------

export default class BrowserRenderer implements ILayerRenderer {
	/** The compiled video JSON being rendered. */
	private videoJSON: VideoJSON;
	/** Runtime layer wrappers. */
	layers: RuntimeBaseLayer[] = [];
	/** The container element for layer DOM elements. */
	private $canvas: HTMLDivElement;
	/** Track whether DOM elements have been set up. */
	private elementsSetup = false;
	/** Frame being rendered right now (for dedup / cancellation). */
	currentFrame = -1;
	/** Whether a frame render is in progress. */
	private rendering = false;
	/** If set, the current render should be interrupted for this frame. */
	private pendingFrame: number | false = false;

	/** Cache of loaded Google Fonts — maps font name → stylesheet URL. */
	loadedFonts: Record<string, string> = {};
	/** Handles @font-face embedding for SVG rasterization passes. */
	private fontEmbedder!: FontEmbedder;

	/** Off-screen canvas used for final frame compositing. */
	private renderCanvas: OffscreenCanvas | null = null;
	/** Per-layer rasterizer (tier selection + cache). Lazily initialised. */
	private rasterizer: LayerRasterizer | null = null;
	/** WebGL compositor for layers with effects. Created lazily on first use. */
	private effectCompositor: WebGLEffectCompositor | null = null;
	/** Overlay canvas per effect layer id, showing the post-effect bitmap. */
	private effectCanvases: Map<string, HTMLCanvasElement> = new Map();

	constructor(videoJSON: VideoJSON) {
		this.videoJSON = videoJSON;

		// Inject renderer CSS into the page if not already present
		if (!document.querySelector('style[data-videoflow-renderer]')) {
			const style = document.createElement('style');
			style.setAttribute('data-videoflow-renderer', '');
			style.textContent = RENDERER_CSS;
			document.head.appendChild(style);
		}

		// Create an off-screen container element for rendering. The live DOM
		// must be attached to `document.body` so headless screenshots (see
		// renderer-server) and any in-browser `getComputedStyle` that drives
		// layer layout has a real layout tree to work against.
		this.$canvas = document.createElement('div');
		this.$canvas.toggleAttribute('data-renderer', true);
		this.$canvas.style.setProperty('--project-width', String(videoJSON.width));
		this.$canvas.style.setProperty('--project-height', String(videoJSON.height));
		this.$canvas.style.position = 'absolute';
		this.$canvas.style.left = '-99999px';
		this.$canvas.style.top = '-99999px';
		this.$canvas.style.overflow = 'hidden';
		document.body.appendChild(this.$canvas);

		// Create runtime layers via the type registry
		for (const layerJSON of videoJSON.layers) {
			this.layers.push(createRuntimeLayer(layerJSON, videoJSON.fps, videoJSON.width, videoJSON.height, this));
		}

		this.fontEmbedder = new FontEmbedder(this.loadedFonts);
	}

	// -----------------------------------------------------------------------
	//  Property definition lookup
	// -----------------------------------------------------------------------

	/**
	 * Look up the full property definitions for a layer type, or a single property.
	 * Used by runtime layers to determine CSS mapping and defaults.
	 */
	getPropertyDefinition(layerType: string): Record<string, PropertyDefinition> | undefined;
	getPropertyDefinition(layerType: string, prop: string): PropertyDefinition | undefined;
	getPropertyDefinition(layerType: string, prop?: string): Record<string, PropertyDefinition> | PropertyDefinition | undefined {
		if (prop !== undefined) {
			return PROPERTIES_BY_TYPE[layerType]?.[prop];
		}
		return PROPERTIES_BY_TYPE[layerType];
	}

	// -----------------------------------------------------------------------
	//  Static render entry point
	// -----------------------------------------------------------------------

	/**
	 * Render a {@link VideoJSON} to a video Blob or ArrayBuffer.
	 *
	 * This is the primary public API.  It creates a BrowserRenderer instance,
	 * initialises all layers, renders every frame, encodes the result via
	 * MediaBunny, and returns the output.
	 *
	 * @param videoJSON - The compiled video JSON.
	 * @param options   - Rendering options (outputType, signal, etc.).
	 * @returns An MP4 Blob (default) or ArrayBuffer.
	 */
	static async render(videoJSON: VideoJSON, options: RenderOptions = {}): Promise<Blob | ArrayBuffer> {
		const renderer = new BrowserRenderer(videoJSON);
		try {
			return await renderer.exportVideo(options);
		} finally {
			renderer.destroy();
		}
	}

	// -----------------------------------------------------------------------
	//  Initialisation
	// -----------------------------------------------------------------------

	/** Initialise all layers — load media, create DOM elements. */
	private async initLayers(): Promise<void> {
		// Load default font
		const defaultFont = 'Noto Sans';
		await this.loadFont(defaultFont);
		this.$canvas.style.setProperty('font-family', `"${defaultFont}", sans-serif`);

		// Initialise each layer (fetch media, decode, extract metadata)
		await Promise.all(this.layers.map(layer => layer.initialize()));

		// Resolve any deferred trimEnd → duration now that intrinsic media
		// durations are known. Must run before any frame is rendered.
		for (const layer of this.layers) {
			layer.resolveMediaTimings();
		}

		this.ensureEffectHiderStyle();

		// Create DOM elements
		this.$canvas.innerHTML = '';
		this.effectCanvases.clear();
		for (const layer of this.layers) {
			if (!this.isLayerEnabled(layer)) continue;
			const $el = await layer.generateElement();
			if ($el) {
				this.$canvas.appendChild($el);
				if (layer instanceof RuntimeGroupLayer) {
					// Mount the group's children into its hidden virtualRoot.
					// Children's DOMs live there (off-screen) so CSS / Web
					// Animations resolve the same as for top-level layers, but
					// the visible / exported DOM stays clean — only the group's
					// composited canvas is at the top level.
					await layer.mountVirtualChildren();
				}
				if (layer.hasEffects) {
					this.mountEffectOverlay(layer, $el);
				}
			}
		}
		this.elementsSetup = true;
	}

	// -----------------------------------------------------------------------
	//  Group support — virtual host & per-child compositor
	// -----------------------------------------------------------------------

	/**
	 * Where group layers should park their hidden child host. For the export
	 * renderer we use `document.body` directly so the children's CSS resolves
	 * against the page's layout context (the same context the main `$canvas`
	 * uses).
	 */
	getVirtualLayerHost(): Node {
		return document.body;
	}

	/**
	 * Composite one layer onto `ctx` (the group's flatten canvas, or any
	 * other caller-owned target sized to the project).
	 *
	 * - **Fast path:** when the layer is tier-1 and has no effects, paints
	 *   the layer's `$element` straight onto `ctx` via `drawDirectInto` —
	 *   no per-layer surface, no extra blit.
	 * - **Normal path:** rasterizes the layer (cached when possible), runs
	 *   the WebGL effect compositor if effects are declared, then
	 *   `drawImage`s the result onto `ctx`.
	 *
	 * Used by `RuntimeGroupLayer.renderFrame` to flatten each child onto the
	 * group's canvas — the same path that `captureFrame` uses for top-level
	 * layers.
	 */
	async compositeLayerInto(
		ctx: OffscreenCanvasRenderingContext2D | CanvasRenderingContext2D,
		layer: RuntimeBaseLayer,
		frame?: number,
	): Promise<void> {
		if (!layer.$element || !layer.lastAppliedProps) return;
		const rasterizer = this.ensureRasterizer();
		const w = this.videoJSON.width;
		const h = this.videoJSON.height;

		ctx.save();
		ctx.globalCompositeOperation = BrowserRenderer.blendModeToCompositeOp(layer.lastAppliedProps.blendMode);

		// Always resolve effects (cheap when none) so transition-injected
		// effects on `props.__effects` engage the pipeline regardless of
		// whether the transition was registered with `injectsEffects: true`.
		const effects = layer.resolveEffectsForProps(layer.lastAppliedProps);
		if (effects.length === 0 && rasterizer.canDrawDirect(layer, layer.lastAppliedProps)) {
			// Fast path — skip the per-layer surface entirely and paint the
			// layer canvas straight onto the group's compositor canvas.
			rasterizer.drawDirectInto(layer, layer.lastAppliedProps, ctx);
			ctx.restore();
			return;
		}
		const surface = await rasterizer.rasterize(layer, layer.lastAppliedProps);
		if (effects.length > 0) {
			if (!this.effectCompositor) {
				this.effectCompositor = new WebGLEffectCompositor(w, h);
			}
			const f = frame ?? this.currentFrame;
			const time = f >= 0 ? f / this.videoJSON.fps : 0;
			const effected = this.effectCompositor.apply(surface, effects, time);
			ctx.drawImage(effected, 0, 0, w, h);
		} else {
			ctx.drawImage(surface, 0, 0, w, h);
		}
		ctx.restore();
	}

	/** Map a CSS blend-mode name to a canvas `globalCompositeOperation` value.
	 *  All CSS names match the Canvas API exactly except `'normal'` → `'source-over'`. */
	private static blendModeToCompositeOp(mode: string | undefined): GlobalCompositeOperation {
		return (!mode || mode === 'normal') ? 'source-over' : mode as GlobalCompositeOperation;
	}

	/**
	 * Inject a document-level style that hides live layer DOM flagged with
	 * `data-effect-layer` inside the renderer container. Hiding via attribute
	 * (not inline style) means the per-frame `resetCSSProperties()` wipe can't
	 * re-expose the layer.
	 */
	private ensureEffectHiderStyle(): void {
		if (document.querySelector('style[data-videoflow-effect-hider]')) return;
		const style = document.createElement('style');
		style.setAttribute('data-videoflow-effect-hider', '');
		style.textContent = '[data-renderer] [data-effect-layer] { visibility: hidden !important; }';
		document.head.appendChild(style);
	}

	/**
	 * Flag the layer's live DOM as hidden and insert a sibling `<canvas>`
	 * right after it. `processEffectLayers()` paints the post-effect bitmap
	 * onto this canvas every frame so `page.screenshot()` (used by
	 * `ServerRenderer`) sees the effected pixels in the live DOM.
	 */
	private mountEffectOverlay(layer: RuntimeBaseLayer, $el: HTMLElement): void {
		$el.setAttribute('data-effect-layer', '');
		const canvas = document.createElement('canvas');
		canvas.width = this.videoJSON.width;
		canvas.height = this.videoJSON.height;
		canvas.setAttribute('data-effect-overlay', layer.json.id);
		// Tag the canvas with the layer id so editor hit-testing (which walks
		// `data-id` in `composedPath`) treats clicks on the overlay as clicks
		// on the layer itself — the source $el is `visibility: hidden`, so it
		// can no longer receive pointer events.
		canvas.setAttribute('data-id', layer.json.id);
		canvas.style.position = 'absolute';
		canvas.style.inset = '0';
		canvas.style.width = '100%';
		canvas.style.height = '100%';
		const track = layer.json.track;
		if (typeof track === 'number') {
			canvas.style.zIndex = String(track + 1);
		}
		if ($el.nextSibling) {
			this.$canvas.insertBefore(canvas, $el.nextSibling);
		} else {
			this.$canvas.appendChild(canvas);
		}
		this.effectCanvases.set(layer.json.id, canvas);
	}

	/** Tear down an effect layer's overlay canvas, if any. */
	private unmountEffectOverlay(layerId: string): void {
		const canvas = this.effectCanvases.get(layerId);
		if (!canvas) return;
		canvas.remove();
		this.effectCanvases.delete(layerId);
	}

	/**
	 * After all layers have rendered this frame, rasterize each effect layer
	 * and paint it through the WebGL compositor onto its overlay canvas.
	 * Clears canvases for effect layers that are out of range this frame.
	 */
	private async processEffectLayers(frame: number): Promise<void> {
		if (this.effectCanvases.size === 0) return;
		const rasterizer = this.ensureRasterizer();
		const width = this.videoJSON.width;
		const height = this.videoJSON.height;
		const time = frame >= 0 ? frame / this.videoJSON.fps : 0;

		this.fontEmbedder.invalidateFrame();

		for (const layer of this.layers) {
			if (!layer.hasEffects) continue;
			const canvas = this.effectCanvases.get(layer.json.id);
			if (!canvas) continue;
			const ctx = canvas.getContext('2d');
			if (!ctx) continue;

			if (!this.isLayerEnabled(layer) || !layer.lastAppliedProps || !layer.$element) {
				ctx.clearRect(0, 0, canvas.width, canvas.height);
				continue;
			}

			const surface = await rasterizer.rasterize(layer, layer.lastAppliedProps);
			ctx.clearRect(0, 0, canvas.width, canvas.height);
			const effects = layer.resolveEffectsForProps(layer.lastAppliedProps);
			if (effects.length > 0) {
				if (!this.effectCompositor) {
					this.effectCompositor = new WebGLEffectCompositor(width, height);
				}
				const effected = this.effectCompositor.apply(surface, effects, time);
				ctx.drawImage(effected, 0, 0, canvas.width, canvas.height);
			} else {
				ctx.drawImage(surface, 0, 0, canvas.width, canvas.height);
			}
		}
	}

	// -----------------------------------------------------------------------
	//  Frame rendering
	// -----------------------------------------------------------------------

	/**
	 * Render a single frame to the DOM.
	 *
	 * Each enabled layer computes its interpolated properties at the given
	 * frame and applies them to its DOM element.
	 */
	async renderFrame(frame: number, force = false): Promise<void> {
		if (frame < 0) return;
		if (!force && frame === this.currentFrame && this.pendingFrame === false) return;
		if (this.rendering) {
			this.pendingFrame = frame;
			return;
		}

		try {
			this.rendering = true;
			if (!this.elementsSetup) await this.initLayers();

			await Promise.all(
				this.layers.map(async layer => {
					if (this.isLayerEnabled(layer)) {
						await layer.renderFrame(frame);
					}
				})
			);

			await this.processEffectLayers(frame);

			this.currentFrame = frame;
			await document.fonts.ready;
		} catch (e) {
			if (e !== 'STOP_RENDERING') throw e;
		} finally {
			this.rendering = false;
			if (this.pendingFrame !== false) {
				const next = this.pendingFrame;
				this.pendingFrame = false;
				await this.renderFrame(next);
			}
		}
	}

	// -----------------------------------------------------------------------
	//  Per-layer frame capture
	// -----------------------------------------------------------------------

	/**
	 * Ensure the LayerRasterizer exists and is wired up to the current
	 * $canvas and font-CSS builder.
	 */
	private ensureRasterizer(): LayerRasterizer {
		if (!this.rasterizer) {
			this.rasterizer = new LayerRasterizer(
				this.videoJSON,
				this.$canvas,
				RENDERER_CSS,
				(layer) => this.buildFontCSSForLayer(layer),
				// Export prioritizes pixel quality: keep Lanczos/bicubic
				// resampling on the per-layer drawImage. Live preview uses
				// `'low'` (the default) for speed.
				{ quality: 'high' },
			);
		}
		return this.rasterizer;
	}

	/**
	 * Build the `@font-face` CSS relevant to one layer. Non-text layers get
	 * an empty string (huge savings when most layers are media). Text-bearing
	 * layers get the full embedded font CSS so SVG foreignObject rasterization
	 * renders with the correct typeface.
	 */
	private async buildFontCSSForLayer(layer: RuntimeBaseLayer): Promise<string> {
		return this.fontEmbedder.buildFontCSSForLayer(layer);
	}

	/**
	 * Capture a single frame onto the shared render canvas.
	 *
	 * 1. Ensure all layer DOMs reflect this frame (via `renderFrame`).
	 * 2. For each enabled, in-range layer, pick the cheapest path:
	 *    - **Fast path (tier-1 + no effects):** paint the layer's `$element`
	 *      directly onto the final canvas via `drawDirectInto` — skips the
	 *      per-layer surface copy entirely.
	 *    - **Normal path:** ask the `LayerRasterizer` for a project-sized
	 *      bitmap (cached when the layer's final props match the previous
	 *      render), pipe through the WebGL effect compositor if the layer
	 *      declares effects, then `drawImage` onto the final canvas.
	 */
	async captureFrame(frame: number): Promise<OffscreenCanvas> {
		await this.renderFrame(frame);

		const width = this.videoJSON.width;
		const height = this.videoJSON.height;
		const time = frame >= 0 ? frame / this.videoJSON.fps : 0;

		if (!this.renderCanvas) {
			this.renderCanvas = new OffscreenCanvas(width, height);
		}
		const ctx = this.renderCanvas.getContext('2d')!;
		ctx.setTransform(1, 0, 0, 1, 0, 0);
		ctx.globalAlpha = 1;
		ctx.clearRect(0, 0, width, height);
		ctx.fillStyle = this.videoJSON.backgroundColor || '#000000';
		ctx.fillRect(0, 0, width, height);

		const rasterizer = this.ensureRasterizer();
		this.fontEmbedder.invalidateFrame();

		for (const layer of this.layers) {
			if (!this.isLayerEnabled(layer)) continue;
			if (!layer.$element) continue;
			if (!layer.lastAppliedProps) continue; // Out of range / hidden this frame

			ctx.save();
			ctx.globalCompositeOperation = BrowserRenderer.blendModeToCompositeOp(layer.lastAppliedProps.blendMode);

			// Always resolve effects (cheap when none) so transition-injected
			// effects on `props.__effects` engage the pipeline regardless of
			// whether the transition was registered with `injectsEffects: true`.
			const effects = layer.resolveEffectsForProps(layer.lastAppliedProps);
			if (effects.length === 0 && rasterizer.canDrawDirect(layer, layer.lastAppliedProps)) {
				// Fast path — paint straight onto the final canvas, skipping
				// the per-layer OffscreenCanvas copy. Saves one full-frame
				// blit per tier-1 layer per frame.
				rasterizer.drawDirectInto(layer, layer.lastAppliedProps, ctx);
				ctx.restore();
				continue;
			}

			const surface = await rasterizer.rasterize(layer, layer.lastAppliedProps);
			if (effects.length > 0) {
				if (!this.effectCompositor) {
					this.effectCompositor = new WebGLEffectCompositor(width, height);
				}
				const effected = this.effectCompositor.apply(surface, effects, time);
				ctx.drawImage(effected, 0, 0, width, height);
			} else {
				ctx.drawImage(surface, 0, 0, width, height);
			}
			ctx.restore();
		}

		return this.renderCanvas;
	}


	// -----------------------------------------------------------------------
	//  Track-aware helpers
	// -----------------------------------------------------------------------

	/**
	 * Whether a layer should be visible/rendered at all.
	 *
	 * Returns `false` when the layer's own `settings.enabled` is false, **or**
	 * when the layer belongs to a track whose `enabled` flag is explicitly
	 * `false` in `videoJSON.tracks`.
	 */
	private isLayerEnabled(layer: RuntimeBaseLayer): boolean {
		if (!layer.json.settings.enabled) return false;
		const { track } = layer.json;
		if (track == null) return true;
		return this.videoJSON.tracks?.[track]?.enabled !== false;
	}

	// -----------------------------------------------------------------------
	//  Audio rendering
	// -----------------------------------------------------------------------

	/**
	 * Render all audio layers into a single AudioBuffer using OfflineAudioContext.
	 *
	 * Each audio/video layer creates a buffer source node with volume and pan
	 * keyframe automation, connected to the context's destination.
	 */
	async renderAudio(): Promise<AudioBuffer | null> {
		const audioLayers = this.layers.filter(l => l.hasAudio && this.isLayerEnabled(l));
		if (audioLayers.length === 0) return null;

		const durationSec = this.videoJSON.duration;
		if (durationSec <= 0) return null;

		// 48 kHz is the universal sample rate for video AAC encoding —
		// 44.1 kHz fails the WebCodecs `AudioEncoder.isConfigSupported`
		// check on some platforms (notably headless Chrome on Linux).
		const sampleRate = 48000;
		const channels = 2;
		const audioCtx = new OfflineAudioContext(channels, Math.ceil(durationSec * sampleRate), sampleRate);

		for (const layer of audioLayers) {
			try {
				await this.generateLayerAudio(layer, audioCtx);
			} catch (e) {
				console.error(`Error generating audio for layer ${layer.json.id}:`, e);
			}
		}

		return await audioCtx.startRendering();
	}

	/**
	 * Generate audio for a single layer and connect it to the audio context.
	 *
	 * Creates a buffer source from the layer's audio data, applies volume
	 * and pan keyframes, and schedules playback.
	 */
	private async generateLayerAudio(layer: RuntimeBaseLayer, audioCtx: OfflineAudioContext): Promise<void> {
		// Prefer audioSource (pre-extracted WAV from server renderer) over
		// source (original container) — headless Chromium's decodeAudioData
		// may not support all container formats (e.g. MP4 video).
		const audioSource = layer.json.settings.audioSource;
		const source = audioSource || layer.json.settings.source;
		if (!source) return;

		// Reuse the layer's pre-decoded AudioBuffer if it has one (audio
		// layers with unresolved sourceEnd decode during initialize()).
		let audioBuffer: AudioBuffer | null = !audioSource
			? ((layer as any).decodedBuffer as AudioBuffer | null) ?? null
			: null;

		if (!audioBuffer) {
			// Decode audio data — try the layer's cached blob first, then
			// acquire a transient ref into the global media cache. Skip the
			// cached blob if an explicit audioSource was provided (it points
			// to a pre-extracted WAV which is more reliable to decode).
			let arrayBuffer: ArrayBuffer;
			const blob = !audioSource ? (layer as any).dataBlob as Blob | null : null;
			let acquiredFromCache = false;
			if (blob) {
				arrayBuffer = await blob.arrayBuffer();
			} else if (!audioSource) {
				const entry = await loadedMedia.acquire(source);
				acquiredFromCache = true;
				arrayBuffer = await entry.blob.arrayBuffer();
			} else {
				const res = await fetch(source);
				arrayBuffer = await res.arrayBuffer();
			}

			try {
				audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);
			} catch (e) {
				// Audio decoding failed — this layer has no decodable audio
				// (e.g., video with no audio track, or unsupported format)
				if (acquiredFromCache) loadedMedia.release(source);
				return;
			}
			if (acquiredFromCache) loadedMedia.release(source);
		}

		const bufferSource = audioCtx.createBufferSource();
		const speed = layer.speed;
		if (speed === 0) return;

		if (speed < 0) {
			// Reverse the audio
			const reversed = audioCtx.createBuffer(
				audioBuffer.numberOfChannels, audioBuffer.length, audioBuffer.sampleRate
			);
			for (let ch = 0; ch < audioBuffer.numberOfChannels; ch++) {
				const data = audioBuffer.getChannelData(ch);
				reversed.copyToChannel(new Float32Array(data).reverse(), ch);
			}
			bufferSource.buffer = reversed;
		} else {
			bufferSource.buffer = audioBuffer;
		}
		bufferSource.playbackRate.value = Math.abs(speed);

		// Volume automation
		const gainNode = audioCtx.createGain();
		gainNode.gain.value = 1;
		this.applyAudioKeyframes(layer, 'volume', gainNode.gain, audioCtx);

		// Pan automation
		const panNode = audioCtx.createStereoPanner();
		panNode.pan.value = 0;
		this.applyAudioKeyframes(layer, 'pan', panNode.pan, audioCtx);

		// Connect chain: source → gain → pan → destination
		bufferSource.connect(gainNode).connect(panNode).connect(audioCtx.destination);

		// Schedule playback. The bufferSource's `duration` argument is in
		// **source seconds** (the buffer's own timing system); combined with
		// `playbackRate = |speed|` it produces `sourceDuration / |speed|`
		// timeline seconds of output, exactly matching the layer footprint.
		const whenSec = layer.startTime;
		const sourceStartSec = layer.sourceStart;
		const sourceDurationSec = layer.sourceDuration;
		let offsetSec: number;
		if (speed < 0) {
			// The buffer was reversed end-to-end above. To play the segment
			// [sourceStart, sourceStart+sourceDuration] in reverse we offset
			// into the reversed buffer by (totalLen − segmentEnd).
			const totalLen = audioBuffer.duration;
			offsetSec = Math.max(0, totalLen - (sourceStartSec + sourceDurationSec));
		} else {
			offsetSec = sourceStartSec;
		}
		bufferSource.start(whenSec, offsetSec, sourceDurationSec);
	}

	/**
	 * Apply keyframe automation to an AudioParam from the layer's animations.
	 *
	 * Keyframes are stored in absolute source seconds; this method projects
	 * each one back into timeline seconds for `setValueAtTime`.
	 */
	private applyAudioKeyframes(
		layer: RuntimeBaseLayer,
		property: string,
		param: AudioParam,
		audioCtx: OfflineAudioContext
	): void {
		const anim = layer.json.animations.find(a => a.property === property);
		if (!anim || anim.keyframes.length === 0) return;

		const startTimeSec = layer.startTime;
		const sourceStartSec = layer.sourceStart;
		const sourceDurationSec = layer.sourceDuration;
		const speed = layer.speed;
		const speedAbs = Math.abs(speed) || 1;

		for (const kf of anim.keyframes) {
			// kf.time is in source seconds (absolute, from start of source).
			const sourceOffsetSec = kf.time - sourceStartSec;
			let timelineSec: number;
			if (speed < 0) {
				timelineSec = startTimeSec + (sourceDurationSec - sourceOffsetSec) / speedAbs;
			} else {
				timelineSec = startTimeSec + sourceOffsetSec / speedAbs;
			}
			if (!Number.isFinite(timelineSec) || timelineSec < 0) continue;
			param.setValueAtTime(Number(kf.value), timelineSec);
		}
	}

	// -----------------------------------------------------------------------
	//  Video export (MediaBunny)
	// -----------------------------------------------------------------------

	/**
	 * Export the full video as an MP4 blob using MediaBunny.
	 *
	 * When `options.worker` is not `false` (the default), SVG rasterisation and
	 * MediaBunny encoding are offloaded to a dedicated Web Worker so that the
	 * main thread stays responsive.  Set `worker: false` to encode entirely on
	 * the main thread (useful when Workers are unavailable).
	 *
	 * @param options - Rendering options including abort signal.
	 * @returns A Blob containing the MP4 video.
	 */
	async exportVideo(options: RenderOptions = {}): Promise<Blob> {
		if (options.worker !== false) {
			return this.exportVideoViaWorker(options);
		}
		return this.exportVideoMainThread(options);
	}

	/**
	 * Main-thread export path (no Worker). Used as fallback when
	 * `options.worker` is explicitly `false`.
	 */
	private async exportVideoMainThread(options: RenderOptions = {}): Promise<Blob> {
		const width = this.videoJSON.width;
		const height = this.videoJSON.height;
		const fps = this.videoJSON.fps;
		const nFrames = Math.round(this.videoJSON.duration * fps);
		const signal = options.signal;
		const onProgress = options.onProgress;

		// Initialise layers
		await this.initLayers();

		// Set up the render canvas
		this.renderCanvas = new OffscreenCanvas(width, height);

		// Render audio first so we know its config before configuring the
		// AAC encoder — some platforms reject specific AAC channel/rate combos.
		if (signal?.aborted) throw new DOMException('Render aborted', 'AbortError');
		const audioBuffer = await this.renderAudio();

		// Create MediaBunny output
		const output = new Output({
			format: new Mp4OutputFormat(),
			target: new BufferTarget(),
		});

		const videoSource = new CanvasSource(this.renderCanvas, {
			codec: 'avc',
			bitrate: QUALITY_HIGH,
		});
		output.addVideoTrack(videoSource, { frameRate: fps });

		// Audio track — only added if the platform supports an audio codec
		// (AAC preferred, Opus fallback). Otherwise we encode silent video
		// instead of failing the whole render.
		let audioSource: AudioBufferSource | null = null;
		if (audioBuffer) {
			const choice = await pickSupportedAudioCodec(audioBuffer.numberOfChannels, audioBuffer.sampleRate);
			if (choice) {
				audioSource = new AudioBufferSource({ codec: choice.codec, bitrate: choice.bitrate });
				output.addAudioTrack(audioSource);
				if (choice.codec === 'opus') {
					console.info(
						`Using Opus audio (${choice.bitrate / 1000} kbps) — AAC not available on this platform.`,
					);
				}
			} else {
				console.warn(
					`No supported audio encoder for ${audioBuffer.numberOfChannels} ch / ${audioBuffer.sampleRate} Hz — encoding silent video.`,
				);
			}
		}

		await output.start();

		if (audioSource && audioBuffer) {
			await audioSource.add(audioBuffer);
			audioSource.close();
		}

		// Render and feed video frames
		for (let frame = 0; frame < nFrames; frame++) {
			if (signal?.aborted) throw new DOMException('Render aborted', 'AbortError');

			await this.captureFrame(frame);
			await videoSource.add(frame / fps, 1 / fps);
			onProgress?.((frame + 1) / nFrames);
		}
		videoSource.close();

		// Finalise
		if (signal?.aborted) throw new DOMException('Render aborted', 'AbortError');
		await output.finalize();
		return new Blob([(output.target as BufferTarget).buffer!], { type: 'video/mp4' });
	}

	// -----------------------------------------------------------------------
	//  Worker-based export
	// -----------------------------------------------------------------------

	/**
	 * Export via a dedicated Web Worker.
	 *
	 * The main thread still owns the DOM and renders each frame to an SVG
	 * string (via {@link buildFrameSVG}).  The SVG strings are posted to the
	 * worker which rasterises them with `createImageBitmap`, draws to an
	 * `OffscreenCanvas`, and feeds MediaBunny for H.264 + AAC encoding.
	 *
	 * Audio channel data is transferred (zero-copy) to the worker which
	 * reconstructs an `AudioBuffer` via `OfflineAudioContext`.
	 */
	private async exportVideoViaWorker(options: RenderOptions = {}): Promise<Blob> {
		const { width, height, fps } = this.videoJSON;
		const nFrames = Math.round(this.videoJSON.duration * fps);
		const { signal, onProgress } = options;

		// Initialise layers (DOM setup — must be on main thread)
		await this.initLayers();

		const workerBlob = new Blob([WORKER_SOURCE], { type: 'text/javascript' });
		const workerUrl = URL.createObjectURL(workerBlob);
		const worker = new Worker(workerUrl, { type: 'module' });

		// -- Promise plumbing for worker replies --------------------------------

		let framesDone = 0;
		let readyResolve!: () => void;
		let doneResolve!: (buf: ArrayBuffer) => void;
		let errorReject!: (err: Error) => void;

		const readyPromise = new Promise<void>(r => { readyResolve = r; });
		const donePromise = new Promise<ArrayBuffer>((resolve, reject) => {
			doneResolve = resolve;
			errorReject = reject;
		});

		worker.onmessage = (e: MessageEvent) => {
			switch (e.data.type) {
				case 'ready':
					readyResolve();
					break;
				case 'frameEncoded':
					framesDone++;
					onProgress?.(framesDone / nFrames);
					break;
				case 'done':
					doneResolve(e.data.buffer);
					break;
				case 'warn':
					console.warn(e.data.message);
					break;
				case 'info':
					console.info(e.data.message);
					break;
				case 'error':
					errorReject(new Error(e.data.message));
					break;
			}
		};

		worker.onerror = (e: ErrorEvent) => {
			errorReject(new Error(e.message));
		};

		// Abort handling — terminate the worker immediately
		if (signal?.aborted) {
			worker.terminate();
			throw new DOMException('Render aborted', 'AbortError');
		}
		const onAbort = () => {
			worker.postMessage({ type: 'abort' });
			worker.terminate();
			errorReject(new DOMException('Render aborted', 'AbortError'));
		};
		signal?.addEventListener('abort', onAbort, { once: true });

		try {
			// 1. Init worker
			worker.postMessage({ type: 'init', width, height, fps });
			await readyPromise;

			// Set up the render canvas (used by captureFrame)
			this.renderCanvas = new OffscreenCanvas(width, height);

			// 2. Render and send audio as raw f32-planar PCM (Web Audio API
			//    is unavailable in workers, so we avoid AudioBuffer entirely).
			const audioBuffer = await this.renderAudio();
			if (audioBuffer) {
				const { numberOfChannels, length, sampleRate } = audioBuffer;
				const data = new Float32Array(numberOfChannels * length);
				for (let i = 0; i < numberOfChannels; i++) {
					data.set(audioBuffer.getChannelData(i), i * length);
				}
				worker.postMessage({
					type: 'audio',
					data,
					sampleRate,
					numberOfChannels,
				}, [data.buffer]);
			} else {
				worker.postMessage({
					type: 'audio',
					data: new Float32Array(0),
					sampleRate: 44100,
					numberOfChannels: 0,
				});
			}

			// 3. Capture frames on main thread (SVG decode requires DOM),
			//    transfer rasterised ImageBitmaps to worker for encoding.
			//    We yield to the event loop between frames so the page stays
			//    responsive (animations, scroll, abort button, etc.).
			for (let frame = 0; frame < nFrames; frame++) {
				if (signal?.aborted) break;
				await new Promise<void>(r => setTimeout(r, 0));
				await this.captureFrame(frame);
				if (signal?.aborted) break;
				const bitmap = this.renderCanvas!.transferToImageBitmap();
				worker.postMessage(
					{ type: 'frame', bitmap, timestamp: frame / fps, duration: 1 / fps },
					[bitmap],
				);
			}

			// 4. Tell worker to finalise encoding
			if (!signal?.aborted) {
				worker.postMessage({ type: 'finalize' });
			}

			const buffer = await donePromise;
			return new Blob([buffer], { type: 'video/mp4' });
		} finally {
			signal?.removeEventListener('abort', onAbort);
			worker.terminate();
			URL.revokeObjectURL(workerUrl);
		}
	}

	// -----------------------------------------------------------------------
	//  Font loading
	// -----------------------------------------------------------------------

	/**
	 * Load a Google Font by name.
	 *
	 * Constructs the exact CSS2 URL for the font using the bundled Google
	 * Fonts registry (axis ranges, italic support, weight variants) so the
	 * request always matches what the API expects — preventing 400 errors
	 * that arise from requesting unsupported axis combinations.
	 */
	async loadFont(fontName: string): Promise<void> {
		if (fontName in this.loadedFonts) return;

		const href = buildFontUrl(fontName);
		if (!href) {
			console.warn(`VideoFlow: font "${fontName}" not found in registry — skipping.`);
			return;
		}

		this.loadedFonts[fontName] = href;

		const sheet = document.createElement('style');
		try {
			const fontSheet = await (await fetch(href, { cache: 'force-cache' })).text();
			sheet.textContent = fontSheet;
			document.head.appendChild(sheet);
		} catch {
			console.error(`VideoFlow: failed to load font "${fontName}"`);
			return;
		}

		try {
			await document.fonts.load(`1em "${fontName}"`);
		} catch {
			console.error(`VideoFlow: font "${fontName}" failed to render`);
		}
	}

	// -----------------------------------------------------------------------
	//  Cleanup
	// -----------------------------------------------------------------------

	/**
	 * Tear down the renderer: destroy every runtime layer (releases media
	 * elements, decoders, audio buffers), remove the hidden `<div data-renderer>`
	 * from the DOM, drop the shared render canvas, and dispose the rasterizer's
	 * per-layer surfaces and the WebGL effect compositor's GL context. Call this
	 * after the last `captureFrame` / `exportVideo` to avoid leaking GL contexts
	 * across repeated renders.
	 */
	destroy(): void {
		for (const layer of this.layers) layer.destroy();
		this.$canvas.remove();
		this.renderCanvas = null;
		if (this.rasterizer) {
			this.rasterizer.destroy();
			this.rasterizer = null;
		}
		if (this.effectCompositor) {
			this.effectCompositor.destroy();
			this.effectCompositor = null;
		}
	}

	// -----------------------------------------------------------------------
	//  Static registries — transitions & effects
	// -----------------------------------------------------------------------

	/**
	 * Register a transition preset. The same registry backs both
	 * `BrowserRenderer` and `DomRenderer`, so a transition registered here is
	 * immediately usable in live preview too.
	 */
	static registerTransition(name: string, fn: TransitionFn): void {
		registerTransitionInRegistry(name, fn);
	}

	/**
	 * Register a GLSL effect. `glsl` is the fragment-shader body implementing
	 * `vec4 effect(sampler2D tex, vec2 uv, vec2 resolution)`; each entry in
	 * `params` becomes a `u_<name>` uniform. Like transitions, the registry is
	 * shared with `DomRenderer`.
	 */
	static registerEffect(
		name: string,
		glsl: string,
		params: Record<string, EffectParamDefinition> = {},
	): void {
		registerEffectInRegistry(name, glsl, params);
	}
}
