/**
 * Pre-build step — bundles BrowserRenderer.worker.ts and all its dependencies
 * (mediabunny) into a single self-contained ESM string, then writes that string
 * as a TypeScript constant to workerBundle.ts.
 *
 * The main BrowserRenderer creates a Blob URL from this constant at runtime,
 * avoiding any file-URL resolution issues across bundlers (esbuild, Vite,
 * webpack, Rollup, etc.).
 *
 * Run: npx tsx src/renderer-browser/bundle-worker.ts
 */

import * as esbuild from 'esbuild';
import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const result = await esbuild.build({
	entryPoints: [path.join(__dirname, 'BrowserRenderer.worker.ts')],
	bundle: true,
	format: 'esm',
	platform: 'browser',
	target: 'esnext',
	write: false,
	minify: true,
	loader: { '.ts': 'ts' },
});

const workerCode = result.outputFiles![0].text;

// Escape backticks and backslashes for embedding in a template literal.
const escaped = workerCode
	.replace(/\\/g, '\\\\')
	.replace(/`/g, '\\`')
	.replace(/\$/g, '\\$');

const output = `// Auto-generated by bundle-worker.ts — do not edit.\nexport default \`${escaped}\`;\n`;

writeFileSync(path.join(__dirname, 'workerBundle.ts'), output, 'utf-8');

console.log(
	`Worker bundle generated (${(workerCode.length / 1024).toFixed(1)} KB minified).`
);
